// Generated by generate.mjs: this package's API on each marketplace.
export const API_TITLE = 'Email Validator with MX and Disposable Check';
export const API_MARKET_SLUG = 'email-validator';
export const RAPIDAPI_HOST = 'email-validator-with-mx-and-disposable-check.p.rapidapi.com';
